@Restaurants.API_HostAddress = https://localhost:7028

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{Restaurants.API_HostAddress}}/api/restaurants

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1

###
POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-1234-3333",
  "City": "Montreal",
  "Street": "123 Main Street",
  "PostalCode": "H1X 1T4"

}

###
PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1002
Content-Type: application/json

{
  "Name": "Updated name",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###
